require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AmendmentsController do

  # This should return the minimal set of attributes required to create a valid
  # Amendment. As you add validations to Amendment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AmendmentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all amendments as @amendments" do
      amendment = Amendment.create! valid_attributes
      get :index, {}, valid_session
      assigns(:amendments).should eq([amendment])
    end
  end

  describe "GET show" do
    it "assigns the requested amendment as @amendment" do
      amendment = Amendment.create! valid_attributes
      get :show, {:id => amendment.to_param}, valid_session
      assigns(:amendment).should eq(amendment)
    end
  end

  describe "GET new" do
    it "assigns a new amendment as @amendment" do
      get :new, {}, valid_session
      assigns(:amendment).should be_a_new(Amendment)
    end
  end

  describe "GET edit" do
    it "assigns the requested amendment as @amendment" do
      amendment = Amendment.create! valid_attributes
      get :edit, {:id => amendment.to_param}, valid_session
      assigns(:amendment).should eq(amendment)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Amendment" do
        expect {
          post :create, {:amendment => valid_attributes}, valid_session
        }.to change(Amendment, :count).by(1)
      end

      it "assigns a newly created amendment as @amendment" do
        post :create, {:amendment => valid_attributes}, valid_session
        assigns(:amendment).should be_a(Amendment)
        assigns(:amendment).should be_persisted
      end

      it "redirects to the created amendment" do
        post :create, {:amendment => valid_attributes}, valid_session
        response.should redirect_to(Amendment.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved amendment as @amendment" do
        # Trigger the behavior that occurs when invalid params are submitted
        Amendment.any_instance.stub(:save).and_return(false)
        post :create, {:amendment => { "user_id" => "invalid value" }}, valid_session
        assigns(:amendment).should be_a_new(Amendment)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Amendment.any_instance.stub(:save).and_return(false)
        post :create, {:amendment => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested amendment" do
        amendment = Amendment.create! valid_attributes
        # Assuming there are no other amendments in the database, this
        # specifies that the Amendment created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Amendment.any_instance.should_receive(:update).with({ "user_id" => "1" })
        put :update, {:id => amendment.to_param, :amendment => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested amendment as @amendment" do
        amendment = Amendment.create! valid_attributes
        put :update, {:id => amendment.to_param, :amendment => valid_attributes}, valid_session
        assigns(:amendment).should eq(amendment)
      end

      it "redirects to the amendment" do
        amendment = Amendment.create! valid_attributes
        put :update, {:id => amendment.to_param, :amendment => valid_attributes}, valid_session
        response.should redirect_to(amendment)
      end
    end

    describe "with invalid params" do
      it "assigns the amendment as @amendment" do
        amendment = Amendment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Amendment.any_instance.stub(:save).and_return(false)
        put :update, {:id => amendment.to_param, :amendment => { "user_id" => "invalid value" }}, valid_session
        assigns(:amendment).should eq(amendment)
      end

      it "re-renders the 'edit' template" do
        amendment = Amendment.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Amendment.any_instance.stub(:save).and_return(false)
        put :update, {:id => amendment.to_param, :amendment => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested amendment" do
      amendment = Amendment.create! valid_attributes
      expect {
        delete :destroy, {:id => amendment.to_param}, valid_session
      }.to change(Amendment, :count).by(-1)
    end

    it "redirects to the amendments list" do
      amendment = Amendment.create! valid_attributes
      delete :destroy, {:id => amendment.to_param}, valid_session
      response.should redirect_to(amendments_url)
    end
  end

end
